//--------------------------------------------------------------------------------
// Auto-generated by LiteX (64cf925b3) on 2024-10-02 19:32:02
//--------------------------------------------------------------------------------
#ifndef __GENERATED_MEM_H
#define __GENERATED_MEM_H

#ifndef WR_WB_SLAVE_BASE
#define WR_WB_SLAVE_BASE 0x20000000L
#define WR_WB_SLAVE_SIZE 0x01000000
#endif

#ifndef ETHMAC_BASE
#define ETHMAC_BASE 0x00020000L
#define ETHMAC_SIZE 0x00002000
#endif

#ifndef ETHMAC_RX_BASE
#define ETHMAC_RX_BASE 0x00020000L
#define ETHMAC_RX_SIZE 0x00001000
#endif

#ifndef ETHMAC_TX_BASE
#define ETHMAC_TX_BASE 0x00021000L
#define ETHMAC_TX_SIZE 0x00001000
#endif

#ifndef CSR_BASE
#define CSR_BASE 0x00000000L
#define CSR_SIZE 0x00010000
#endif

#ifndef MEM_REGIONS
#define MEM_REGIONS "WR_WB_SLAVE  0x20000000 0x1000000 \nETHMAC       0x00020000 0x2000 \nETHMAC_RX    0x00020000 0x1000 \nETHMAC_TX    0x00021000 0x1000 \nCSR          0x00000000 0x10000 "
#endif
#endif
