//--------------------------------------------------------------------------------
// Auto-generated by LiteX (9c07b45f) on 2024-06-27 19:03:56
//--------------------------------------------------------------------------------
#ifndef __GENERATED_MEM_H
#define __GENERATED_MEM_H

#ifndef WR_BASE
#define WR_BASE 0x20000000L
#define WR_SIZE 0x01000000
#endif

#ifndef CSR_BASE
#define CSR_BASE 0x00000000L
#define CSR_SIZE 0x00010000
#endif

#ifndef MEM_REGIONS
#define MEM_REGIONS "WR   0x20000000 0x1000000 \nCSR  0x00000000 0x10000 "
#endif
#endif
