//--------------------------------------------------------------------------------
// Auto-generated by LiteX (10dcc7367) on 2024-11-22 13:11:11
//--------------------------------------------------------------------------------
#ifndef __GENERATED_MEM_H
#define __GENERATED_MEM_H

#ifndef WR_WB_SLAVE_BASE
#define WR_WB_SLAVE_BASE 0x20000000L
#define WR_WB_SLAVE_SIZE 0x01000000
#endif

#ifndef ETHMAC0_BASE
#define ETHMAC0_BASE 0x00020000L
#define ETHMAC0_SIZE 0x00002000
#endif

#ifndef ETHMAC0_RX_BASE
#define ETHMAC0_RX_BASE 0x00020000L
#define ETHMAC0_RX_SIZE 0x00001000
#endif

#ifndef ETHMAC0_TX_BASE
#define ETHMAC0_TX_BASE 0x00021000L
#define ETHMAC0_TX_SIZE 0x00001000
#endif

#ifndef CSR_BASE
#define CSR_BASE 0x00000000L
#define CSR_SIZE 0x00010000
#endif

#ifndef MEM_REGIONS
#define MEM_REGIONS "WR_WB_SLAVE  0x20000000 0x1000000 \nETHMAC0      0x00020000 0x2000 \nETHMAC0_RX   0x00020000 0x1000 \nETHMAC0_TX   0x00021000 0x1000 \nCSR          0x00000000 0x10000 "
#endif
#endif
