//--------------------------------------------------------------------------------
// Auto-generated by LiteX (ec06bf595) on 2024-12-03 15:33:56
//--------------------------------------------------------------------------------
#ifndef __GENERATED_SOC_H
#define __GENERATED_SOC_H
#define CONFIG_PLATFORM_NAME "spec_a7_wr_nic"
#define CONFIG_CLOCK_FREQUENCY 125000000
#define CONFIG_CPU_TYPE_NONE
#define CONFIG_CPU_VARIANT_STANDARD
#define CONFIG_CPU_FAMILY
#define CONFIG_CPU_NAME
#define CONFIG_CPU_HUMAN_NAME "Unknown"
#define CONFIG_IDENTIFIER "LiteX-WR-NIC on SPEC-A7. 2024-12-03 15:33:55"
#define DMA_CHANNELS 1
#define DMA_ADDR_WIDTH 32
#define ETHMAC0_RX_INTERRUPT 0
#define ETHMAC0_TX_INTERRUPT 1
#define CONFIG_CSR_DATA_WIDTH 32
#define CONFIG_CSR_ALIGNMENT 32
#define CONFIG_BUS_STANDARD "wishbone"
#define CONFIG_BUS_DATA_WIDTH 32
#define CONFIG_BUS_ADDRESS_WIDTH 32
#define CONFIG_BUS_BURSTING 0
#define ETHMAC0_RX_SLOTS 4
#define ETHMAC0_TX_SLOTS 4
#define ETHMAC0_SLOT_SIZE 2048

#endif
