//--------------------------------------------------------------------------------
// Auto-generated by LiteX (9c07b45f) on 2024-06-27 14:39:30
//--------------------------------------------------------------------------------
#ifndef __GENERATED_MEM_H
#define __GENERATED_MEM_H

#ifndef ETHMAC_BASE
#define ETHMAC_BASE 0x00020000L
#define ETHMAC_SIZE 0x00020000
#endif

#ifndef ETHMAC_RX_BASE
#define ETHMAC_RX_BASE 0x00020000L
#define ETHMAC_RX_SIZE 0x00010000
#endif

#ifndef ETHMAC_TX_BASE
#define ETHMAC_TX_BASE 0x00030000L
#define ETHMAC_TX_SIZE 0x00010000
#endif

#ifndef CSR_BASE
#define CSR_BASE 0x00000000L
#define CSR_SIZE 0x00010000
#endif

#ifndef MEM_REGIONS
#define MEM_REGIONS "ETHMAC     0x00020000 0x20000 \nETHMAC_RX  0x00020000 0x10000 \nETHMAC_TX  0x00030000 0x10000 \nCSR        0x00000000 0x10000 "
#endif
#endif
