//--------------------------------------------------------------------------------
// Auto-generated by LiteX (6e9dffdbf) on 2024-09-19 16:46:46
//--------------------------------------------------------------------------------
#ifndef __GENERATED_MEM_H
#define __GENERATED_MEM_H

#ifndef ETHMAC_BASE
#define ETHMAC_BASE 0x00020000L
#define ETHMAC_SIZE 0x00004000
#endif

#ifndef ETHMAC_RX_BASE
#define ETHMAC_RX_BASE 0x00020000L
#define ETHMAC_RX_SIZE 0x00002000
#endif

#ifndef ETHMAC_TX_BASE
#define ETHMAC_TX_BASE 0x00022000L
#define ETHMAC_TX_SIZE 0x00002000
#endif

#ifndef CSR_BASE
#define CSR_BASE 0x00000000L
#define CSR_SIZE 0x00010000
#endif

#ifndef MEM_REGIONS
#define MEM_REGIONS "ETHMAC     0x00020000 0x4000 \nETHMAC_RX  0x00020000 0x2000 \nETHMAC_TX  0x00022000 0x2000 \nCSR        0x00000000 0x10000 "
#endif
#endif
