//--------------------------------------------------------------------------------
// Auto-generated by LiteX (3dd3477e) on 2024-06-26 19:01:32
//--------------------------------------------------------------------------------
#ifndef __GENERATED_MEM_H
#define __GENERATED_MEM_H

#ifndef CSR_BASE
#define CSR_BASE 0x00000000L
#define CSR_SIZE 0x00010000
#endif

#ifndef MEM_REGIONS
#define MEM_REGIONS "CSR  0x00000000 0x10000 "
#endif
#endif
