//--------------------------------------------------------------------------------
// Auto-generated by LiteX (14a64030) on 2024-06-25 19:20:30
//--------------------------------------------------------------------------------
#ifndef __GENERATED_SOC_H
#define __GENERATED_SOC_H
#define CONFIG_PLATFORM_NAME "acorn"
#define CONFIG_CLOCK_FREQUENCY 125000000
#define CONFIG_CPU_TYPE_NONE
#define CONFIG_CPU_VARIANT_STANDARD
#define CONFIG_CPU_FAMILY
#define CONFIG_CPU_NAME
#define CONFIG_CPU_HUMAN_NAME "Unknown"
#define CONFIG_IDENTIFIER "LiteX SoC on Acorn CLE-101/215(+) 2024-06-25 19:16:20"
#define ETHMAC_RX_WAIT_OFFSET 0
#define ETHMAC_TX_READY_OFFSET 1
#define DMA_CHANNELS 1
#define DMA_ADDR_WIDTH 32
#define ETHRX_INTERRUPT 0
#define ETHTX_INTERRUPT 1
#define CONFIG_CSR_DATA_WIDTH 32
#define CONFIG_CSR_ALIGNMENT 32
#define CONFIG_BUS_STANDARD "wishbone"
#define CONFIG_BUS_DATA_WIDTH 32
#define CONFIG_BUS_ADDRESS_WIDTH 32
#define CONFIG_BUS_BURSTING 0
#define ETHMAC_RX_SLOTS 32
#define ETHMAC_TX_SLOTS 32
#define ETHMAC_SLOT_SIZE 2048

#endif
