//--------------------------------------------------------------------------------
// Auto-generated by LiteX (3864615f) on 2024-04-18 11:24:29
//--------------------------------------------------------------------------------
#ifndef __GENERATED_SOC_H
#define __GENERATED_SOC_H
#define CONFIG_CLOCK_FREQUENCY 125000000
#define CONFIG_CPU_TYPE_NONE
#define CONFIG_CPU_VARIANT_STANDARD
#define CONFIG_CPU_NAME
#define CONFIG_CPU_HUMAN_NAME "Unknown"
#define CONFIG_BIOS_NO_BUILD_TIME
#define ETHMAC_RX_WAIT_OFFSET 0
#define ETHMAC_TX_READY_OFFSET 1
#define DMA_CHANNELS 0
#define DMA_ADDR_WIDTH 32
#define ETHRX_INTERRUPT 0
#define ETHTX_INTERRUPT 1
#define CONFIG_CSR_DATA_WIDTH 32
#define CONFIG_CSR_ALIGNMENT 32
#define CONFIG_BUS_STANDARD "wishbone"
#define CONFIG_BUS_DATA_WIDTH 32
#define CONFIG_BUS_ADDRESS_WIDTH 32
#define CONFIG_BUS_BURSTING 0
#define ETHMAC_RX_SLOTS 32
#define ETHMAC_TX_SLOTS 32
#define ETHMAC_SLOT_SIZE 2048

#endif
